# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import coordinator_pb2 as coordinator__pb2
from . import wiggle_pb2 as wiggle__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in coordinator_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CellCoordinatorStub:
    """The optional cell coordinator's control plane. It shards a workflow's instances across isolated
    cells; it is never on the data path (poll/complete go straight to a cell). See
    docs/cell-coordinator-tickets.md and the design reference for the full model.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FetchConfig = channel.unary_unary(
                '/dev.wiggle.proto.CellCoordinator/FetchConfig',
                request_serializer=coordinator__pb2.FetchConfigRequest.SerializeToString,
                response_deserializer=coordinator__pb2.NodeConfig.FromString,
                _registered_method=True)
        self.Register = channel.unary_unary(
                '/dev.wiggle.proto.CellCoordinator/Register',
                request_serializer=coordinator__pb2.RegisterRequest.SerializeToString,
                response_deserializer=coordinator__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/dev.wiggle.proto.CellCoordinator/Heartbeat',
                request_serializer=coordinator__pb2.CoordinatorHeartbeatRequest.SerializeToString,
                response_deserializer=coordinator__pb2.CoordinatorHeartbeatResponse.FromString,
                _registered_method=True)
        self.Deregister = channel.unary_unary(
                '/dev.wiggle.proto.CellCoordinator/Deregister',
                request_serializer=coordinator__pb2.DeregisterRequest.SerializeToString,
                response_deserializer=wiggle__pb2.Empty.FromString,
                _registered_method=True)
        self.Resolve = channel.unary_unary(
                '/dev.wiggle.proto.CellCoordinator/Resolve',
                request_serializer=coordinator__pb2.ResolveRequest.SerializeToString,
                response_deserializer=coordinator__pb2.ResolveResponse.FromString,
                _registered_method=True)
        self.ActiveCells = channel.unary_unary(
                '/dev.wiggle.proto.CellCoordinator/ActiveCells',
                request_serializer=coordinator__pb2.ActiveCellsRequest.SerializeToString,
                response_deserializer=coordinator__pb2.ActiveCellsResponse.FromString,
                _registered_method=True)
        self.OpenEpoch = channel.unary_unary(
                '/dev.wiggle.proto.CellCoordinator/OpenEpoch',
                request_serializer=coordinator__pb2.OpenEpochRequest.SerializeToString,
                response_deserializer=coordinator__pb2.Policy.FromString,
                _registered_method=True)
        self.SetRing = channel.unary_unary(
                '/dev.wiggle.proto.CellCoordinator/SetRing',
                request_serializer=coordinator__pb2.SetRingRequest.SerializeToString,
                response_deserializer=coordinator__pb2.Policy.FromString,
                _registered_method=True)
        self.RegisterWorkflow = channel.unary_unary(
                '/dev.wiggle.proto.CellCoordinator/RegisterWorkflow',
                request_serializer=coordinator__pb2.RegisterWorkflowRequest.SerializeToString,
                response_deserializer=coordinator__pb2.RegisterWorkflowResponse.FromString,
                _registered_method=True)
        self.DeregisterWorkflow = channel.unary_unary(
                '/dev.wiggle.proto.CellCoordinator/DeregisterWorkflow',
                request_serializer=coordinator__pb2.DeregisterWorkflowRequest.SerializeToString,
                response_deserializer=coordinator__pb2.DeregisterWorkflowResponse.FromString,
                _registered_method=True)
        self.ListWorkflows = channel.unary_unary(
                '/dev.wiggle.proto.CellCoordinator/ListWorkflows',
                request_serializer=coordinator__pb2.ListWorkflowsRequest.SerializeToString,
                response_deserializer=coordinator__pb2.ListWorkflowsResponse.FromString,
                _registered_method=True)


class CellCoordinatorServicer:
    """The optional cell coordinator's control plane. It shards a workflow's instances across isolated
    cells; it is never on the data path (poll/complete go straight to a cell). See
    docs/cell-coordinator-tickets.md and the design reference for the full model.
    """

    def FetchConfig(self, request, context):
        """---- node lifecycle (a server node <-> coordinator) ----
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Deregister(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Resolve(self, request, context):
        """---- resolution (clients & workers; cached, region-aware) ----
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActiveCells(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenEpoch(self, request, context):
        """---- admin (reconfiguration & definition fan-out) ----
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetRing(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterWorkflow(self, request, context):
        """R23
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeregisterWorkflow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListWorkflows(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CellCoordinatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FetchConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchConfig,
                    request_deserializer=coordinator__pb2.FetchConfigRequest.FromString,
                    response_serializer=coordinator__pb2.NodeConfig.SerializeToString,
            ),
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=coordinator__pb2.RegisterRequest.FromString,
                    response_serializer=coordinator__pb2.RegisterResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=coordinator__pb2.CoordinatorHeartbeatRequest.FromString,
                    response_serializer=coordinator__pb2.CoordinatorHeartbeatResponse.SerializeToString,
            ),
            'Deregister': grpc.unary_unary_rpc_method_handler(
                    servicer.Deregister,
                    request_deserializer=coordinator__pb2.DeregisterRequest.FromString,
                    response_serializer=wiggle__pb2.Empty.SerializeToString,
            ),
            'Resolve': grpc.unary_unary_rpc_method_handler(
                    servicer.Resolve,
                    request_deserializer=coordinator__pb2.ResolveRequest.FromString,
                    response_serializer=coordinator__pb2.ResolveResponse.SerializeToString,
            ),
            'ActiveCells': grpc.unary_unary_rpc_method_handler(
                    servicer.ActiveCells,
                    request_deserializer=coordinator__pb2.ActiveCellsRequest.FromString,
                    response_serializer=coordinator__pb2.ActiveCellsResponse.SerializeToString,
            ),
            'OpenEpoch': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenEpoch,
                    request_deserializer=coordinator__pb2.OpenEpochRequest.FromString,
                    response_serializer=coordinator__pb2.Policy.SerializeToString,
            ),
            'SetRing': grpc.unary_unary_rpc_method_handler(
                    servicer.SetRing,
                    request_deserializer=coordinator__pb2.SetRingRequest.FromString,
                    response_serializer=coordinator__pb2.Policy.SerializeToString,
            ),
            'RegisterWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWorkflow,
                    request_deserializer=coordinator__pb2.RegisterWorkflowRequest.FromString,
                    response_serializer=coordinator__pb2.RegisterWorkflowResponse.SerializeToString,
            ),
            'DeregisterWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.DeregisterWorkflow,
                    request_deserializer=coordinator__pb2.DeregisterWorkflowRequest.FromString,
                    response_serializer=coordinator__pb2.DeregisterWorkflowResponse.SerializeToString,
            ),
            'ListWorkflows': grpc.unary_unary_rpc_method_handler(
                    servicer.ListWorkflows,
                    request_deserializer=coordinator__pb2.ListWorkflowsRequest.FromString,
                    response_serializer=coordinator__pb2.ListWorkflowsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dev.wiggle.proto.CellCoordinator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dev.wiggle.proto.CellCoordinator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CellCoordinator:
    """The optional cell coordinator's control plane. It shards a workflow's instances across isolated
    cells; it is never on the data path (poll/complete go straight to a cell). See
    docs/cell-coordinator-tickets.md and the design reference for the full model.
    """

    @staticmethod
    def FetchConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dev.wiggle.proto.CellCoordinator/FetchConfig',
            coordinator__pb2.FetchConfigRequest.SerializeToString,
            coordinator__pb2.NodeConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dev.wiggle.proto.CellCoordinator/Register',
            coordinator__pb2.RegisterRequest.SerializeToString,
            coordinator__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dev.wiggle.proto.CellCoordinator/Heartbeat',
            coordinator__pb2.CoordinatorHeartbeatRequest.SerializeToString,
            coordinator__pb2.CoordinatorHeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Deregister(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dev.wiggle.proto.CellCoordinator/Deregister',
            coordinator__pb2.DeregisterRequest.SerializeToString,
            wiggle__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Resolve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dev.wiggle.proto.CellCoordinator/Resolve',
            coordinator__pb2.ResolveRequest.SerializeToString,
            coordinator__pb2.ResolveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ActiveCells(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dev.wiggle.proto.CellCoordinator/ActiveCells',
            coordinator__pb2.ActiveCellsRequest.SerializeToString,
            coordinator__pb2.ActiveCellsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OpenEpoch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dev.wiggle.proto.CellCoordinator/OpenEpoch',
            coordinator__pb2.OpenEpochRequest.SerializeToString,
            coordinator__pb2.Policy.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetRing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dev.wiggle.proto.CellCoordinator/SetRing',
            coordinator__pb2.SetRingRequest.SerializeToString,
            coordinator__pb2.Policy.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dev.wiggle.proto.CellCoordinator/RegisterWorkflow',
            coordinator__pb2.RegisterWorkflowRequest.SerializeToString,
            coordinator__pb2.RegisterWorkflowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeregisterWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dev.wiggle.proto.CellCoordinator/DeregisterWorkflow',
            coordinator__pb2.DeregisterWorkflowRequest.SerializeToString,
            coordinator__pb2.DeregisterWorkflowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListWorkflows(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dev.wiggle.proto.CellCoordinator/ListWorkflows',
            coordinator__pb2.ListWorkflowsRequest.SerializeToString,
            coordinator__pb2.ListWorkflowsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
