# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import wiggle_pb2 as wiggle__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in wiggle_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WiggleControlPlaneStub:
    """The control-plane API. Workers pull work from here; nothing is ever pushed to them,
    so workers need no inbound connectivity and can scale independently of the servers.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HealthCheck = channel.unary_unary(
                '/dev.wiggle.proto.WiggleControlPlane/HealthCheck',
                request_serializer=wiggle__pb2.Empty.SerializeToString,
                response_deserializer=wiggle__pb2.HealthStatus.FromString,
                _registered_method=True)
        self.GetCluster = channel.unary_unary(
                '/dev.wiggle.proto.WiggleControlPlane/GetCluster',
                request_serializer=wiggle__pb2.Empty.SerializeToString,
                response_deserializer=wiggle__pb2.ClusterView.FromString,
                _registered_method=True)
        self.ListWorkflows = channel.unary_unary(
                '/dev.wiggle.proto.WiggleControlPlane/ListWorkflows',
                request_serializer=wiggle__pb2.Empty.SerializeToString,
                response_deserializer=wiggle__pb2.WorkflowNames.FromString,
                _registered_method=True)
        self.RegisterWorkflow = channel.unary_unary(
                '/dev.wiggle.proto.WiggleControlPlane/RegisterWorkflow',
                request_serializer=wiggle__pb2.WorkflowDefinition.SerializeToString,
                response_deserializer=wiggle__pb2.RegisterWorkflowResult.FromString,
                _registered_method=True)
        self.GetWorkflow = channel.unary_unary(
                '/dev.wiggle.proto.WiggleControlPlane/GetWorkflow',
                request_serializer=wiggle__pb2.GetWorkflowRequest.SerializeToString,
                response_deserializer=wiggle__pb2.WorkflowDefinition.FromString,
                _registered_method=True)
        self.StartInstance = channel.unary_unary(
                '/dev.wiggle.proto.WiggleControlPlane/StartInstance',
                request_serializer=wiggle__pb2.StartInstanceRequest.SerializeToString,
                response_deserializer=wiggle__pb2.StartInstanceResult.FromString,
                _registered_method=True)
        self.ListInstances = channel.unary_unary(
                '/dev.wiggle.proto.WiggleControlPlane/ListInstances',
                request_serializer=wiggle__pb2.ListInstancesRequest.SerializeToString,
                response_deserializer=wiggle__pb2.InstanceList.FromString,
                _registered_method=True)
        self.GetInstance = channel.unary_unary(
                '/dev.wiggle.proto.WiggleControlPlane/GetInstance',
                request_serializer=wiggle__pb2.InstanceIdRequest.SerializeToString,
                response_deserializer=wiggle__pb2.InstanceDetail.FromString,
                _registered_method=True)
        self.CancelInstance = channel.unary_unary(
                '/dev.wiggle.proto.WiggleControlPlane/CancelInstance',
                request_serializer=wiggle__pb2.CancelInstanceRequest.SerializeToString,
                response_deserializer=wiggle__pb2.CancelInstanceResult.FromString,
                _registered_method=True)
        self.SignalInstance = channel.unary_unary(
                '/dev.wiggle.proto.WiggleControlPlane/SignalInstance',
                request_serializer=wiggle__pb2.SignalRequest.SerializeToString,
                response_deserializer=wiggle__pb2.Ack.FromString,
                _registered_method=True)
        self.CreateSchedule = channel.unary_unary(
                '/dev.wiggle.proto.WiggleControlPlane/CreateSchedule',
                request_serializer=wiggle__pb2.CreateScheduleRequest.SerializeToString,
                response_deserializer=wiggle__pb2.ScheduleView.FromString,
                _registered_method=True)
        self.ListSchedules = channel.unary_unary(
                '/dev.wiggle.proto.WiggleControlPlane/ListSchedules',
                request_serializer=wiggle__pb2.Empty.SerializeToString,
                response_deserializer=wiggle__pb2.ScheduleList.FromString,
                _registered_method=True)
        self.DeleteSchedule = channel.unary_unary(
                '/dev.wiggle.proto.WiggleControlPlane/DeleteSchedule',
                request_serializer=wiggle__pb2.ScheduleIdRequest.SerializeToString,
                response_deserializer=wiggle__pb2.Ack.FromString,
                _registered_method=True)
        self.PollTasks = channel.unary_unary(
                '/dev.wiggle.proto.WiggleControlPlane/PollTasks',
                request_serializer=wiggle__pb2.PollRequest.SerializeToString,
                response_deserializer=wiggle__pb2.TaskList.FromString,
                _registered_method=True)
        self.CompleteTask = channel.unary_unary(
                '/dev.wiggle.proto.WiggleControlPlane/CompleteTask',
                request_serializer=wiggle__pb2.TaskResultRequest.SerializeToString,
                response_deserializer=wiggle__pb2.Ack.FromString,
                _registered_method=True)
        self.FailTask = channel.unary_unary(
                '/dev.wiggle.proto.WiggleControlPlane/FailTask',
                request_serializer=wiggle__pb2.TaskFailureRequest.SerializeToString,
                response_deserializer=wiggle__pb2.Ack.FromString,
                _registered_method=True)
        self.HeartbeatTask = channel.unary_unary(
                '/dev.wiggle.proto.WiggleControlPlane/HeartbeatTask',
                request_serializer=wiggle__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=wiggle__pb2.HeartbeatResult.FromString,
                _registered_method=True)
        self.AdvanceRun = channel.unary_unary(
                '/dev.wiggle.proto.WiggleControlPlane/AdvanceRun',
                request_serializer=wiggle__pb2.AdvanceRunRequest.SerializeToString,
                response_deserializer=wiggle__pb2.AdvanceRunResult.FromString,
                _registered_method=True)


class WiggleControlPlaneServicer:
    """The control-plane API. Workers pull work from here; nothing is ever pushed to them,
    so workers need no inbound connectivity and can scale independently of the servers.
    """

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCluster(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListWorkflows(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterWorkflow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWorkflow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartInstance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListInstances(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInstance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelInstance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SignalInstance(self, request, context):
        """Delivers a named signal to a running instance; the payload merges into its context.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSchedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSchedules(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSchedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PollTasks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FailTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HeartbeatTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AdvanceRun(self, request, context):
        """Applies an ordered run of locally-executed steps atomically, keeps the lease, and reports
        whether the worker should keep going (LOCAL_SYNC / LOCAL_ASYNC execution).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WiggleControlPlaneServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=wiggle__pb2.Empty.FromString,
                    response_serializer=wiggle__pb2.HealthStatus.SerializeToString,
            ),
            'GetCluster': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCluster,
                    request_deserializer=wiggle__pb2.Empty.FromString,
                    response_serializer=wiggle__pb2.ClusterView.SerializeToString,
            ),
            'ListWorkflows': grpc.unary_unary_rpc_method_handler(
                    servicer.ListWorkflows,
                    request_deserializer=wiggle__pb2.Empty.FromString,
                    response_serializer=wiggle__pb2.WorkflowNames.SerializeToString,
            ),
            'RegisterWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWorkflow,
                    request_deserializer=wiggle__pb2.WorkflowDefinition.FromString,
                    response_serializer=wiggle__pb2.RegisterWorkflowResult.SerializeToString,
            ),
            'GetWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWorkflow,
                    request_deserializer=wiggle__pb2.GetWorkflowRequest.FromString,
                    response_serializer=wiggle__pb2.WorkflowDefinition.SerializeToString,
            ),
            'StartInstance': grpc.unary_unary_rpc_method_handler(
                    servicer.StartInstance,
                    request_deserializer=wiggle__pb2.StartInstanceRequest.FromString,
                    response_serializer=wiggle__pb2.StartInstanceResult.SerializeToString,
            ),
            'ListInstances': grpc.unary_unary_rpc_method_handler(
                    servicer.ListInstances,
                    request_deserializer=wiggle__pb2.ListInstancesRequest.FromString,
                    response_serializer=wiggle__pb2.InstanceList.SerializeToString,
            ),
            'GetInstance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInstance,
                    request_deserializer=wiggle__pb2.InstanceIdRequest.FromString,
                    response_serializer=wiggle__pb2.InstanceDetail.SerializeToString,
            ),
            'CancelInstance': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelInstance,
                    request_deserializer=wiggle__pb2.CancelInstanceRequest.FromString,
                    response_serializer=wiggle__pb2.CancelInstanceResult.SerializeToString,
            ),
            'SignalInstance': grpc.unary_unary_rpc_method_handler(
                    servicer.SignalInstance,
                    request_deserializer=wiggle__pb2.SignalRequest.FromString,
                    response_serializer=wiggle__pb2.Ack.SerializeToString,
            ),
            'CreateSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSchedule,
                    request_deserializer=wiggle__pb2.CreateScheduleRequest.FromString,
                    response_serializer=wiggle__pb2.ScheduleView.SerializeToString,
            ),
            'ListSchedules': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSchedules,
                    request_deserializer=wiggle__pb2.Empty.FromString,
                    response_serializer=wiggle__pb2.ScheduleList.SerializeToString,
            ),
            'DeleteSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSchedule,
                    request_deserializer=wiggle__pb2.ScheduleIdRequest.FromString,
                    response_serializer=wiggle__pb2.Ack.SerializeToString,
            ),
            'PollTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.PollTasks,
                    request_deserializer=wiggle__pb2.PollRequest.FromString,
                    response_serializer=wiggle__pb2.TaskList.SerializeToString,
            ),
            'CompleteTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteTask,
                    request_deserializer=wiggle__pb2.TaskResultRequest.FromString,
                    response_serializer=wiggle__pb2.Ack.SerializeToString,
            ),
            'FailTask': grpc.unary_unary_rpc_method_handler(
                    servicer.FailTask,
                    request_deserializer=wiggle__pb2.TaskFailureRequest.FromString,
                    response_serializer=wiggle__pb2.Ack.SerializeToString,
            ),
            'HeartbeatTask': grpc.unary_unary_rpc_method_handler(
                    servicer.HeartbeatTask,
                    request_deserializer=wiggle__pb2.HeartbeatRequest.FromString,
                    response_serializer=wiggle__pb2.HeartbeatResult.SerializeToString,
            ),
            'AdvanceRun': grpc.unary_unary_rpc_method_handler(
                    servicer.AdvanceRun,
                    request_deserializer=wiggle__pb2.AdvanceRunRequest.FromString,
                    response_serializer=wiggle__pb2.AdvanceRunResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dev.wiggle.proto.WiggleControlPlane', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dev.wiggle.proto.WiggleControlPlane', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WiggleControlPlane:
    """The control-plane API. Workers pull work from here; nothing is ever pushed to them,
    so workers need no inbound connectivity and can scale independently of the servers.
    """

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dev.wiggle.proto.WiggleControlPlane/HealthCheck',
            wiggle__pb2.Empty.SerializeToString,
            wiggle__pb2.HealthStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCluster(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dev.wiggle.proto.WiggleControlPlane/GetCluster',
            wiggle__pb2.Empty.SerializeToString,
            wiggle__pb2.ClusterView.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListWorkflows(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dev.wiggle.proto.WiggleControlPlane/ListWorkflows',
            wiggle__pb2.Empty.SerializeToString,
            wiggle__pb2.WorkflowNames.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dev.wiggle.proto.WiggleControlPlane/RegisterWorkflow',
            wiggle__pb2.WorkflowDefinition.SerializeToString,
            wiggle__pb2.RegisterWorkflowResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dev.wiggle.proto.WiggleControlPlane/GetWorkflow',
            wiggle__pb2.GetWorkflowRequest.SerializeToString,
            wiggle__pb2.WorkflowDefinition.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartInstance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dev.wiggle.proto.WiggleControlPlane/StartInstance',
            wiggle__pb2.StartInstanceRequest.SerializeToString,
            wiggle__pb2.StartInstanceResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListInstances(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dev.wiggle.proto.WiggleControlPlane/ListInstances',
            wiggle__pb2.ListInstancesRequest.SerializeToString,
            wiggle__pb2.InstanceList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetInstance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dev.wiggle.proto.WiggleControlPlane/GetInstance',
            wiggle__pb2.InstanceIdRequest.SerializeToString,
            wiggle__pb2.InstanceDetail.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelInstance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dev.wiggle.proto.WiggleControlPlane/CancelInstance',
            wiggle__pb2.CancelInstanceRequest.SerializeToString,
            wiggle__pb2.CancelInstanceResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SignalInstance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dev.wiggle.proto.WiggleControlPlane/SignalInstance',
            wiggle__pb2.SignalRequest.SerializeToString,
            wiggle__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dev.wiggle.proto.WiggleControlPlane/CreateSchedule',
            wiggle__pb2.CreateScheduleRequest.SerializeToString,
            wiggle__pb2.ScheduleView.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSchedules(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dev.wiggle.proto.WiggleControlPlane/ListSchedules',
            wiggle__pb2.Empty.SerializeToString,
            wiggle__pb2.ScheduleList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dev.wiggle.proto.WiggleControlPlane/DeleteSchedule',
            wiggle__pb2.ScheduleIdRequest.SerializeToString,
            wiggle__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PollTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dev.wiggle.proto.WiggleControlPlane/PollTasks',
            wiggle__pb2.PollRequest.SerializeToString,
            wiggle__pb2.TaskList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dev.wiggle.proto.WiggleControlPlane/CompleteTask',
            wiggle__pb2.TaskResultRequest.SerializeToString,
            wiggle__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FailTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dev.wiggle.proto.WiggleControlPlane/FailTask',
            wiggle__pb2.TaskFailureRequest.SerializeToString,
            wiggle__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HeartbeatTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dev.wiggle.proto.WiggleControlPlane/HeartbeatTask',
            wiggle__pb2.HeartbeatRequest.SerializeToString,
            wiggle__pb2.HeartbeatResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AdvanceRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dev.wiggle.proto.WiggleControlPlane/AdvanceRun',
            wiggle__pb2.AdvanceRunRequest.SerializeToString,
            wiggle__pb2.AdvanceRunResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
